services:
  dagster:
    build: .
    container_name: dagster
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      DAGSTER_HOME: /opt/dagster_home
    volumes:
      - ./workspace.yaml:/opt/app/workspace.yaml
    command: dagster api grpc -h 0.0.0.0 -p 3000

  postgres:
    image: postgres:15
    container_name: dagster-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster123
      POSTGRES_DB: dagster_db
    restart: unless-stopped

